#!/usr/bin/env node

require.paths.unshift('lib');
require.paths.unshift('lib/connect/lib');

var argv = require('optimist').argv,
    env = argv.env ? '.' + argv.env : '',
    db = require('./config/db' + env),
    loader = require('./lib/loader');
    
function init(db) {
  return loader(__dirname + '/modules', {
                  console: console,
                  setTimeout: setTimeout,
                  setInterval: setInterval,
                  clearTimeout: clearTimeout,
                  clearIntevral: clearInterval,
                  db: db,
                  modules: '?'
                });
}

db(init);
