#!/usr/bin/env node

var argv = require('optimist').argv,
    env = argv.env ? '.' + argv.env : '',
    db = require('./config/db' + env),
    loader = require('./lib/loader');
    
function init(db) {
  return loader(__dirname + '/modules', {
                  db: db,
                  modules: '?'
                });
}

db(init);
