#!/usr/bin/env node

var connect = require('connect'),
    io = require('socket.io'),
    route_api = require('./lib/routes/api'),
    route_user = require('./lib/routes/user');
    
var server = connect.createServer(
  connect.bodyDecoder(),
  connect.format(),
  connect.compiler(),
  connect.session(),
  connect.router(route_user)
  connect.router(route_api)
);
